# Generated by Django 5.2 on 2026-03-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("Owner", "Owner"),
                    ("tenant", "Tenant"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
