# Generated by Django 5.2 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("landlord", "Landlord"),
                    ("agent", "Agent"),
                    ("tenant", "Tenant"),
                    ("manager", "Manager"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
