# Generated by Django 5.2 on 2026-04-22 13:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="CM", max_length=2, verbose_name="Country"
            ),
        ),
    ]
