# Generated by Django 5.2 on 2026-05-07 07:58

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
        ("tenants", "0005_tenant_tenants_ten_is_disc_b7a12b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("assigned", "Assigned to vendor"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimated cost (XAF)",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual cost (XAF)",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (French)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_maintenance",
                        to="properties.manager",
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "requested_by_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="properties.manager",
                        verbose_name="Requested by (manager)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="tenants.tenant",
                        verbose_name="Requested by (tenant)",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance request",
                "verbose_name_plural": "Maintenance requests",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequestImage",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="maintenance_requests", verbose_name="Image"
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="maintenance.maintenancerequest",
                        verbose_name="Maintenance request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance request image",
                "verbose_name_plural": "Maintenance request images",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company name"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Contact person"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Specialties"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "company_name_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company name (French)"
                    ),
                ),
                (
                    "contact_name_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Contact person (French)",
                    ),
                ),
                (
                    "address_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address (French)"
                    ),
                ),
                (
                    "specialties_fr",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Specialties (French)"
                    ),
                ),
                (
                    "notes_fr",
                    models.TextField(blank=True, verbose_name="Notes (French)"),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "indexes": [
                    models.Index(fields=["phone"], name="maintenance_phone_558616_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="assigned_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_requests",
                to="maintenance.vendor",
                verbose_name="Assigned vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["unit", "status"], name="maintenance_unit_id_3b432c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority"], name="maintenance_priorit_ec7e12_idx"
            ),
        ),
    ]
