# Generated by Django 5.2 on 2026-03-12 21:05

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("properties", "__first__"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "interval_months",
                    models.PositiveSmallIntegerField(
                        help_text="Number of months between payments (1 = monthly, 3 = quarterly, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Interval (months)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Payment term",
                "verbose_name_plural": "Payment terms",
                "ordering": ["interval_months"],
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Start date"),
                ),
                ("end_date", models.DateField(db_index=True, verbose_name="End date")),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Amount due each payment period (e.g., 600,000 XAF for 12 months)",
                        max_digits=10,
                        verbose_name="Rent amount per interval (XAF)",
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of the month when payment is due (e.g., 1st, 5th)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Due day of month",
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Security deposit (XAF)",
                    ),
                ),
                (
                    "deposit_paid",
                    models.BooleanField(default=False, verbose_name="Deposit paid"),
                ),
                (
                    "late_fee_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount (XAF)"),
                            ("percentage", "Percentage of rent"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Late fee type",
                    ),
                ),
                (
                    "late_fee_value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Amount in XAF or percentage points",
                        max_digits=10,
                        verbose_name="Late fee value",
                    ),
                ),
                (
                    "utilities_included",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Utilities included"
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Document URLs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                            ("renewed", "Renewed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, verbose_name="Termination reason"),
                ),
                (
                    "renewed_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewed_to",
                        to="rentals.lease",
                        verbose_name="Renewed from",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease",
                "verbose_name_plural": "Leases",
            },
        ),
        migrations.CreateModel(
            name="LeaseTenant",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary tenant"),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Signed at"
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_tenants",
                        to="rentals.lease",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_tenants",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease tenant",
                "verbose_name_plural": "Lease tenants",
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="tenants",
            field=models.ManyToManyField(
                related_name="leases",
                through="rentals.LeaseTenant",
                to="tenants.tenant",
                verbose_name="Tenants",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Amount (XAF)"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(db_index=True, verbose_name="Payment date"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mtn_momo", "MTN MoMo"),
                            ("orange_money", "Orange Money"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("deposit", "Security deposit"),
                            ("fee", "Fee / penalty"),
                            ("utility", "Utility bill"),
                            ("other", "Other"),
                        ],
                        default="rent",
                        max_length=20,
                        verbose_name="Payment type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start date of the rental period this payment covers",
                        verbose_name="Period start",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="End date of the rental period this payment covers",
                        verbose_name="Period end",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mobile provider"
                    ),
                ),
                (
                    "mobile_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Payer phone number",
                    ),
                ),
                (
                    "mobile_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Mobile money reference",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank name"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Check number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway response"
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="rentals.lease",
                        verbose_name="Lease",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tenants.tenant",
                        verbose_name="Paying tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="payment_term",
            field=models.ForeignKey(
                help_text="How often rent is due (monthly, quarterly, yearly, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="rentals.paymentterm",
                verbose_name="Payment term",
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company name"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Contact person"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Specialties"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "company_name_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company name (French)"
                    ),
                ),
                (
                    "contact_name_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Contact person (French)",
                    ),
                ),
                (
                    "address_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address (French)"
                    ),
                ),
                (
                    "specialties_fr",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Specialties (French)"
                    ),
                ),
                (
                    "notes_fr",
                    models.TextField(blank=True, verbose_name="Notes (French)"),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "indexes": [
                    models.Index(fields=["phone"], name="rentals_ven_phone_b2f941_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("assigned", "Assigned to vendor"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Photo URLs"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimated cost (XAF)",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual cost (XAF)",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (French)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_maintenance",
                        to="properties.manager",
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "requested_by_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="properties.manager",
                        verbose_name="Requested by (manager)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="tenants.tenant",
                        verbose_name="Requested by (tenant)",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "assigned_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="rentals.vendor",
                        verbose_name="Assigned vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance request",
                "verbose_name_plural": "Maintenance requests",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance / repairs"),
                            ("utility", "Utility (water/electricity)"),
                            ("tax", "Property tax"),
                            ("insurance", "Insurance"),
                            ("management_fee", "Management fee"),
                            ("other", "Other"),
                        ],
                        default="maintenance",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Amount (XAF)"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(db_index=True, verbose_name="Expense date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Receipt",
                    ),
                ),
                (
                    "is_reimbursable",
                    models.BooleanField(
                        default=False, verbose_name="Reimbursable by tenant"
                    ),
                ),
                (
                    "reimbursed",
                    models.BooleanField(default=False, verbose_name="Reimbursed"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="properties.unit",
                        verbose_name="Unit (optional)",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="rentals.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Document name"),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/%Y/%m/", verbose_name="File"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="rentals_doc_content_117779_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="leasetenant",
            index=models.Index(
                fields=["lease", "tenant"], name="rentals_lea_lease_i_50621c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leasetenant",
            unique_together={("lease", "tenant")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["lease", "payment_date"], name="rentals_pay_lease_i_2194e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="rentals_pay_transac_69b056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="rentals_pay_status_b42e0a_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="rentals_pay_period__09fe53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["unit", "start_date", "end_date"],
                name="rentals_lea_unit_id_265e5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["status"], name="rentals_lea_status_abb50e_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["payment_term"], name="rentals_lea_payment_fff8e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["unit", "status"], name="rentals_mai_unit_id_a35416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority"], name="rentals_mai_priorit_10eead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["property", "expense_date"],
                name="rentals_exp_propert_58931b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="rentals_exp_categor_e21548_idx"
            ),
        ),
    ]
