# Generated by Django 5.2 on 2026-03-09 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="anguage",
            new_name="language",
        ),
    ]
