# Generated by Django 5.2 on 2026-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0002_rename_anguage_vendor_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment building"),
                    ("house", "Single family house"),
                    ("commercial", "Commercial (shop/office)"),
                    ("land", "Land"),
                    ("hostel", "Hostel"),
                    ("other", "Other"),
                ],
                default="apartment",
                max_length=20,
                verbose_name="Property type",
            ),
        ),
    ]
