# Generated by Django 5.2 on 2026-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Primary tenant"),
        ),
    ]
