# Generated by Django 5.2 on 2026-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscriptionplan_subscriptioninvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="platform_fee_cap_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If set, replaces the global platform fee cap for this plan.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="transaction_fee_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage discount applied to platform fee (e.g., 25.00 for 25% off).",
                max_digits=5,
            ),
        ),
    ]
