# Generated by Django 5.2 on 2026-05-07 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance / repairs"),
                            ("utility", "Utility (water/electricity)"),
                            ("tax", "Property tax"),
                            ("insurance", "Insurance"),
                            ("management_fee", "Management fee"),
                            ("other", "Other"),
                        ],
                        default="maintenance",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Amount (XAF)"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(db_index=True, verbose_name="Expense date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Receipt",
                    ),
                ),
                (
                    "is_reimbursable",
                    models.BooleanField(
                        default=False, verbose_name="Reimbursable by tenant"
                    ),
                ),
                (
                    "reimbursed",
                    models.BooleanField(default=False, verbose_name="Reimbursed"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="properties.unit",
                        verbose_name="Unit (optional)",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="maintenance.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "indexes": [
                    models.Index(
                        fields=["property", "expense_date"],
                        name="reports_exp_propert_951ece_idx",
                    ),
                    models.Index(
                        fields=["category"], name="reports_exp_categor_b26d81_idx"
                    ),
                ],
            },
        ),
    ]
