# Generated by Django 5.2 on 2026-05-07 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateConfig",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Payment Receipt"),
                            ("agreement", "Rental Agreement"),
                            ("report", "Financial Report"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "selected_layout",
                    models.IntegerField(
                        choices=[
                            (1, "Layout 1"),
                            (2, "Layout 2"),
                            (3, "Layout 3"),
                            (4, "Layout 4"),
                            (5, "Layout 5"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Only one template per type per landlord can be default.",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/logos/"
                    ),
                ),
                ("primary_color", models.CharField(default="#1E3A8A", max_length=7)),
                ("secondary_color", models.CharField(default="#F59E0B", max_length=7)),
                ("agency_name", models.CharField(blank=True, max_length=255)),
                ("agency_address", models.TextField(blank=True)),
                ("agency_phone", models.CharField(blank=True, max_length=30)),
                ("agency_email", models.EmailField(blank=True, max_length=254)),
                ("footer_text", models.TextField(blank=True)),
                ("show_property_name", models.BooleanField(default=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="properties.owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Configuration",
                "verbose_name_plural": "Template Configurations",
                "indexes": [
                    models.Index(
                        fields=["landlord", "template_type"],
                        name="reports_tem_landlor_d43699_idx",
                    )
                ],
                "unique_together": {("landlord", "template_type", "is_default")},
            },
        ),
    ]
