# Generated by Django 5.2 on 2026-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
        ("reports", "0002_templateconfig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="templateconfig",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="templateconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("landlord", "template_type"),
                name="unique_default_template_per_landlord_type",
            ),
        ),
    ]
