# Generated by Django 5.2 on 2026-05-07 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
        ("reports", "0003_alter_templateconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="maintenance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="maintenance.maintenancerequest",
                verbose_name="Maintenance request",
            ),
        ),
    ]
