# Generated by Django 5.2 on 2026-03-12 19:06

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary tenant"),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=50, verbose_name="ID number (CNI/Passport)"
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tenants/ids/",
                        verbose_name="ID scan",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Emergency contact name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Emergency contact phone",
                    ),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Relationship"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Employer"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Job title"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Monthly income (XAF)",
                    ),
                ),
                (
                    "guarantor_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Guarantor name"
                    ),
                ),
                (
                    "guarantor_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Guarantor phone",
                    ),
                ),
                (
                    "guarantor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Guarantor email"
                    ),
                ),
                (
                    "guarantor_id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tenants/guarantors/",
                        verbose_name="Guarantor ID scan",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "emergency_contact_name_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Emergency contact name (French)",
                    ),
                ),
                (
                    "employer_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Employer (French)"
                    ),
                ),
                (
                    "job_title_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Job title (French)"
                    ),
                ),
                (
                    "notes_fr",
                    models.TextField(blank=True, verbose_name="Notes (French)"),
                ),
                (
                    "guarantor_name_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Guarantor name (French)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "indexes": [
                    models.Index(
                        fields=["user"], name="tenants_ten_user_id_91a8a2_idx"
                    ),
                    models.Index(
                        fields=["id_number"], name="tenants_ten_id_numb_2adb77_idx"
                    ),
                ],
            },
        ),
    ]
