# Generated by Django 5.2 on 2026-03-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="id_document_back",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tenants/ids/",
                verbose_name="ID back scan",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="id_document_front",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tenants/ids/",
                verbose_name="ID front scan",
            ),
        ),
    ]
