# Generated by Django 5.2 on 2026-03-31 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenant_id_document_back_tenant_id_document_front"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="id_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="ID number (CNI/Passport)"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("id_number",), name="unique_tenant_id_number"
            ),
        ),
    ]
