# Generated by Django 5.2 on 2026-03-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_tenant_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_discoverable",
            field=models.BooleanField(
                default=True,
                help_text="Allow landlords/managers to find this tenant via search.",
                verbose_name="Is Discoverable",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
    ]
