# Generated by Django 5.2 on 2026-03-31 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_tenant_is_discoverable_tenant_is_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["is_discoverable"], name="tenants_ten_is_disc_b7a12b_idx"
            ),
        ),
    ]
