from celery import shared_task
from apps.payments.services import DisbursementService
from apps.payments.models import Payment
from apps.payments.receipt_service import ReceiptService
from apps.payments.models import Receipt
from apps.notifications.tasks import send_notification
from django.conf import settings
import logging

logger = logging.getLogger(__name__)


@shared_task
def process_disbursements():
    service = DisbursementService()
    service.process_pending_disbursements()
    logger.info("Disbursements processed")
    

@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def generate_receipt_task(self, payment_id: str):
    """
    Generate a receipt for a given payment.
    Creates or updates a Receipt record.
    """
    try:
        payment = Payment.objects.get(id=payment_id)
    except Payment.DoesNotExist:
        logger.error(f"Payment {payment_id} not found for receipt generation.")
        return

    # Ensure a Receipt record exists (pending status)
    receipt, created = Receipt.objects.get_or_create(
        payment=payment,
        defaults={
            "receipt_number": "",  # will be generated by service
            "status": "pending",
        }
    )

    service = ReceiptService()
    try:
        # This will generate receipt data and update the receipt record
        service.create_receipt(payment)
        logger.info(f"Receipt generated for payment {payment_id}")
    except Exception as e:
        logger.exception(f"Failed to generate receipt for payment {payment_id}")
        # Mark receipt as failed
        receipt.status = "failed"
        receipt.error_message = str(e)[:255]
        receipt.save(update_fields=["status", "error_message"])
        # Retry with exponential backoff
        if self.request.retries < self.max_retries:
            raise self.retry(exc=e, countdown=60 * (2 ** self.request.retries))
        
@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def send_receipt_email(self, payment_id: str, recipient_email: str, tenant_name: str, receipt_data: dict):
    """
    Send receipt email to tenant asynchronously.
    """
    try:
        frontend_url = settings.FRONTEND_URL
        receipt_url = f"{frontend_url}/receipts/{payment_id}/"

        # Extract payment details
        payment_info = receipt_data.get("payment", {})
        period_start = payment_info.get("period_start")
        period_end = payment_info.get("period_end")
        months_covered = payment_info.get("months_covered")

        # Format a human-readable period
        if period_start and period_end:
            # Convert "2026-07-01" to "July 2026" or similar
            from datetime import datetime
            start_dt = datetime.fromisoformat(period_start)
            end_dt = datetime.fromisoformat(period_end)
            # If it's a full month, show month name
            if start_dt.day == 1 and end_dt.day == end_dt.replace(day=1, month=end_dt.month+1, year=end_dt.year).day - 1:
                # likely full month
                period_display = f"{start_dt.strftime('%B %Y')}"
            else:
                period_display = f"{start_dt.strftime('%d %b %Y')} – {end_dt.strftime('%d %b %Y')}"
        else:
            period_display = "N/A"

        send_notification.delay(
            channel="email",
            recipient=recipient_email,
            subject=f"Receipt for payment #{receipt_data.get('receipt_number', payment_id[:8])}",
            template_name="emails/payments/receipt.html",
            context={
                "tenant_name": tenant_name,
                "amount": payment_info.get("amount"),
                "property_name": receipt_data["property"]["name"],
                "unit_number": receipt_data["unit"]["number"],
                "receipt_number": receipt_data["receipt_number"],
                "payment_date": payment_info.get("payment_date"),
                "payment_method": payment_info.get("payment_method"),
                "period_display": period_display,          # ✅ New
                "period_start": period_start,             # ✅ New
                "period_end": period_end,                 # ✅ New
                "months_covered": months_covered,         # ✅ New
                "receipt_url": receipt_url,
            }
        )
        logger.info(f"Receipt email dispatched to {recipient_email} for payment {payment_id}")

    except Exception as e:
        logger.exception(f"Failed to send receipt email for payment {payment_id}")
        if self.request.retries < self.max_retries:
            raise self.retry(exc=e, countdown=60 * (2 ** self.request.retries))
