# Generated by Django 5.2 on 2026-03-12 21:06

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Property name"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment building"),
                            ("house", "Single family house"),
                            ("commercial", "Commercial (shop/office)"),
                            ("land", "Land"),
                            ("hostel", "Hostel"),
                            ("other", "Other"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Property type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Region"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="CM", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal code"
                    ),
                ),
                (
                    "has_generator",
                    models.BooleanField(default=False, verbose_name="Has generator"),
                ),
                (
                    "has_water_tank",
                    models.BooleanField(default=False, verbose_name="Has water tank"),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Amenities"
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Image URLs"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        help_text="Language of the main text fields (name, description, amenities)",
                        max_length=2,
                        verbose_name="Original language",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (French)"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "amenities_fr",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Amenities (French)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_payout_method",
                    models.CharField(
                        choices=[
                            ("mtn_momo", "MTN MoMo"),
                            ("orange_money", "Orange Money"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Preferred payout method",
                    ),
                ),
                (
                    "mobile_money_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="For MoMo/Orange payouts",
                        max_length=30,
                        null=True,
                        region=None,
                        verbose_name="Mobile money number",
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Bank account name"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank name"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Account number"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bank code / SWIFT"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'Identification Unique",
                        max_length=50,
                        verbose_name="Tax ID (NIU)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Commission rate (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "managed_properties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managers",
                        to="properties.property",
                        verbose_name="Managed properties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
        ),
        migrations.CreateModel(
            name="PropertyOwnership",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Ownership percentage",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary owner"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_records",
                        to="properties.owner",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_records",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property ownership",
                "verbose_name_plural": "Property ownerships",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="owners",
            field=models.ManyToManyField(
                related_name="properties",
                through="properties.PropertyOwnership",
                to="properties.owner",
                verbose_name="Owners",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_number",
                    models.CharField(max_length=50, verbose_name="Unit number / name"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1_bed", "1 bedroom"),
                            ("2_bed", "2 bedrooms"),
                            ("3_bed", "3 bedrooms"),
                            ("shop", "Shop"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        default="1_bed",
                        max_length=20,
                        verbose_name="Unit type",
                    ),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Floor"
                    ),
                ),
                (
                    "size_m2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Size (m²)"
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Bedrooms"
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Bathrooms"
                    ),
                ),
                (
                    "default_rent_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Default amount per payment interval (if no lease override)",
                        max_digits=10,
                        verbose_name="Default rent amount (XAF)",
                    ),
                ),
                (
                    "default_security_deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Default security deposit (XAF)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="vacant",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Amenities"
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Image URLs"
                    ),
                ),
                (
                    "water_meter_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Water meter number"
                    ),
                ),
                (
                    "electricity_meter_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Electricity meter number",
                    ),
                ),
                (
                    "has_prepaid_meter",
                    models.BooleanField(default=False, verbose_name="Prepaid meter"),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Custom fields"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "amenities_fr",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Amenities (French)"
                    ),
                ),
                (
                    "default_payment_term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default interval for this unit (e.g., monthly, yearly)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="payments.paymentterm",
                        verbose_name="Default payment term",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(fields=["user"], name="properties__user_id_781d3b_idx"),
        ),
        migrations.AddIndex(
            model_name="manager",
            index=models.Index(fields=["user"], name="properties__user_id_cb534a_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyownership",
            index=models.Index(
                fields=["property", "owner"], name="properties__propert_677e91_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyownership",
            unique_together={("property", "owner")},
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["name"], name="properties__name_47b1ec_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["city"], name="properties__city_74fa1a_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_active"], name="properties__is_acti_78cc81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["property", "status"], name="properties__propert_41331e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["unit_number"], name="properties__unit_nu_b8deee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("property", "unit_number")},
        ),
    ]
