# Generated by Django 5.2 on 2026-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="occupancy",
            field=models.PositiveIntegerField(default=0, verbose_name="Occupancy"),
        ),
    ]
