# Generated by Django 5.2 on 2026-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_unit_occupancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="occupancy",
        ),
        migrations.AddField(
            model_name="property",
            name="occupancy",
            field=models.PositiveIntegerField(default=0, verbose_name="Occupancy"),
        ),
    ]
