# Generated by Django 5.2 on 2026-03-18 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_remove_unit_occupancy_property_occupancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="occupancy",
        ),
    ]
