# Generated by Django 5.2 on 2026-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_remove_property_occupancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("MAINTENANCE", "Maintenance"), ("ACTIVE", "Active")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
