# Generated by Django 5.2 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="starting_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Starting amount",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="top_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Top amount"
            ),
        ),
    ]
