# Generated by Django 5.2 on 2026-03-21 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_remove_property_images_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.JSONField(blank=True, default=list, verbose_name="Image URLs"),
        ),
        migrations.CreateModel(
            name="UnitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/units/")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_images",
                        to="properties.unit",
                    ),
                ),
            ],
        ),
    ]
