# Generated by Django 5.2 on 2026-03-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_property_images_unitimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alt text"),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Primary image"),
        ),
    ]
