# Generated by Django 5.2 on 2026-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_unitimage_alt_text_unitimage_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment_unit", "Apartment (Single Unit)"),
                    ("apartment_building", "Apartment Building"),
                    ("villa", "Villa"),
                    ("house", "House"),
                    ("duplex", "Duplex"),
                    ("studio", "Studio"),
                    ("land", "Land"),
                    ("shop", "Shop / Store"),
                    ("office", "Office"),
                    ("commercial", "Commercial Space"),
                    ("hostel", "Hostel / Student Housing"),
                    ("other", "Other"),
                ],
                default="apartment_unit",
                max_length=20,
                verbose_name="Property type",
            ),
        ),
    ]
