# Generated by Django 5.2 on 2026-04-20 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0011_alter_property_property_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="default_payment_term",
        ),
    ]
