# Generated by Django 5.2 on 2026-04-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_delete_paymentterm_alter_installment_order_index_and_more"),
        ("properties", "0012_remove_unit_default_payment_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="default_payment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentplan",
            ),
        ),
    ]
