# Generated by Django 5.2 on 2026-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0013_unit_default_payment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="monthly_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Monthly rent (XAF)",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="year_rented",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=4,
                null=True,
                verbose_name="Year rented",
            ),
        ),
    ]
