# Generated by Django 5.2 on 2026-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0014_unit_monthly_rent_unit_year_rented"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="year_rented",
            new_name="yearly_rent",
        ),
    ]
