# Generated by Django 5.2 on 2026-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0015_rename_year_rented_unit_yearly_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="yearly_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Year rented",
            ),
        ),
    ]
