# Generated by Django 5.2 on 2026-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0016_alter_unit_yearly_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="rent_duration_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
                verbose_name="Rent duration type",
            ),
        ),
    ]
