# Generated by Django 5.2 on 2026-04-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0017_unit_rent_duration_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_transaction", "Per‑transaction fees"),
                            (
                                "subscription",
                                "Monthly subscription (no per‑transaction fees)",
                            ),
                        ],
                        default="per_transaction",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_subscription_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="XAF per month, charged to landlord",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee_cap",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum platform fee (XAF)"
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="% of rent (capped by platform_fee_cap)",
                        max_digits=5,
                    ),
                ),
                (
                    "gateway_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="% on the amount disbursed to landlord",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant pays"),
                            ("landlord", "Landlord pays"),
                            ("split", "Shared (50/50)"),
                        ],
                        default="tenant",
                        max_length=10,
                    ),
                ),
                (
                    "gateway_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant pays"),
                            ("landlord", "Landlord pays"),
                            ("split", "Shared (50/50)"),
                        ],
                        default="tenant",
                        max_length=10,
                    ),
                ),
                (
                    "fixed_extra_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Fixed fee added to tenant total",
                        max_digits=10,
                    ),
                ),
                (
                    "gateway_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g., ['mtn_momo', 'orange_money'] – leave empty to never charge gateway fee",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Configuration",
                "verbose_name_plural": "Payment Configurations",
            },
        ),
    ]
