# Generated by Django 5.2 on 2026-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0018_paymentconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentconfiguration",
            options={},
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="fixed_extra_fee",
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="gateway_fee_percent",
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="platform_fee_cap",
        ),
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="platform_fee_percent",
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="gateway_fee_payer",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("split", "Split"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="gateway_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="monthly_subscription_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="platform_fee_payer",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("split", "Split"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("per_transaction", "Per-transaction"),
                    ("subscription", "Subscription"),
                ],
                default="per_transaction",
                max_length=20,
            ),
        ),
    ]
