# Generated by Django 5.2 on 2026-05-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_subscriptionplan"),
        ("properties", "0019_alter_paymentconfiguration_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentconfiguration",
            name="monthly_subscription_fee",
        ),
        migrations.AddField(
            model_name="paymentconfiguration",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if pricing_model = 'subscription'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="gateway_fee_payer",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("split", "Shared"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="platform_fee_payer",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("split", "Shared"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfiguration",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("per_transaction", "Per‑transaction"),
                    ("subscription", "Subscription"),
                ],
                default="per_transaction",
                max_length=20,
            ),
        ),
    ]
