# Generated by Django 5.2 on 2026-05-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_alter_subscriptionplan_options_and_more"),
        (
            "properties",
            "0020_remove_paymentconfiguration_monthly_subscription_fee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="subscription_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="subscription_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trial", "Trial"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
