# Generated by Django 5.2 on 2026-06-23 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0012_alter_paymentplan_options_paymentplan_owner_and_more"),
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
        ("subscriptions", "0002_subscriptionplan_subscriptioninvoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="OwnerPaymentConfig",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Platform Fee (%)",
                    ),
                ),
                (
                    "platform_fee_cap",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Platform Fee Cap (XAF)"
                    ),
                ),
                (
                    "gateway_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Gateway Fee (%)",
                    ),
                ),
                (
                    "fixed_extra_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Fixed Extra Fee (XAF)",
                    ),
                ),
                (
                    "platform_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Platform Fee Payer",
                    ),
                ),
                (
                    "gateway_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Gateway Fee Payer",
                    ),
                ),
                (
                    "wallet_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Wallet Fee Payer",
                    ),
                ),
                (
                    "gateway_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g., ['mtn_momo', 'orange_money']",
                        verbose_name="Gateway Methods",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_transaction", "Per‑transaction"),
                            ("subscription", "Subscription"),
                        ],
                        default="per_transaction",
                        max_length=20,
                        verbose_name="Pricing Model",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="properties.owner",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner Payment Config",
                "verbose_name_plural": "Owner Payment Configs",
            },
        ),
        migrations.CreateModel(
            name="PropertyPaymentConfig",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_transaction", "Per‑transaction"),
                            ("subscription", "Subscription"),
                        ],
                        default="per_transaction",
                        max_length=20,
                        verbose_name="Pricing Model",
                    ),
                ),
                (
                    "platform_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Platform Fee Payer",
                    ),
                ),
                (
                    "gateway_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Gateway Fee Payer",
                    ),
                ),
                (
                    "wallet_fee_payer",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("landlord", "Landlord"),
                            ("split", "Split 50/50"),
                        ],
                        default="tenant",
                        max_length=10,
                        verbose_name="Wallet Fee Payer",
                    ),
                ),
                (
                    "gateway_methods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Gateway Methods"
                    ),
                ),
                (
                    "fee_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override rates, caps, fixed fees for this property. Example: {'platform_fee_percent': 0.5, 'platform_fee_cap': 500}",
                        verbose_name="Fee Overrides",
                    ),
                ),
                (
                    "enable_wallet_payments",
                    models.BooleanField(
                        default=True, verbose_name="Enable Wallet Payments"
                    ),
                ),
                (
                    "allow_manual_payments",
                    models.BooleanField(
                        default=False, verbose_name="Allow Manual Payments"
                    ),
                ),
                (
                    "manual_payment_requires_verification",
                    models.BooleanField(
                        default=True,
                        verbose_name="Manual Payment Requires Tenant Verification",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("XAF", "XAF"), ("USD", "USD"), ("EUR", "EUR")],
                        default="XAF",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "default_payment_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template copied when a new rental agreement is created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_properties",
                        to="payments.paymentplan",
                        verbose_name="Default Payment Plan",
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_payment_config",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Payment Config",
                "verbose_name_plural": "Property Payment Configs",
            },
        ),
        migrations.DeleteModel(
            name="PaymentConfiguration",
        ),
    ]
