# Generated by Django 5.2 on 2026-06-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0013_auditlog_disbursement_idempotencykey_ledgerentry_and_more"),
        (
            "properties",
            "0022_alter_owner_subscription_plan_ownerpaymentconfig_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOwnerSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.owner",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_splits",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
