# Generated by Django 5.2 on 2026-06-27 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0023_paymentownersplit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermTemplate",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Template name"),
                ),
                (
                    "content",
                    models.TextField(verbose_name="Terms and conditions content"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_templates",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Template",
                "verbose_name_plural": "Term Templates",
                "ordering": ["name"],
            },
        ),
    ]
