# Generated by Django 5.2 on 2026-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0024_termtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="payment_pin",
            field=models.CharField(
                blank=True,
                help_text="Hashed PIN for manual payment authorization.",
                max_length=128,
                null=True,
                verbose_name="Payment Pin",
            ),
        ),
    ]
