# Generated by Django 5.2 on 2026-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("platform_fee_cap", models.PositiveIntegerField(default=1000)),
                (
                    "gateway_fee_percent",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
                (
                    "fixed_extra_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("gateway_methods", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]
