# Generated by Django 5.2 on 2026-03-12 21:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "interval_months",
                    models.PositiveSmallIntegerField(
                        help_text="Number of months between payments (1 = monthly, 3 = quarterly, etc.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Interval (months)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Payment term",
                "verbose_name_plural": "Payment terms",
                "ordering": ["interval_months"],
            },
        ),
    ]
