# Generated by Django 5.2 on 2026-04-20 23:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("properties", "0012_remove_unit_default_payment_term"),
        ("tenants", "0005_tenant_tenants_ten_is_disc_b7a12b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Plan name")),
                (
                    "mode",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "allowed_monthly_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of integers, e.g., [1,3,6]. Empty means any up to max_months.",
                        verbose_name="Allowed month multiples",
                    ),
                ),
                (
                    "max_months",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Maximum months per payment"
                    ),
                ),
                (
                    "show_full_payment_option",
                    models.BooleanField(
                        default=True, verbose_name="Show full yearly payment option"
                    ),
                ),
                (
                    "enforce_installment_order",
                    models.BooleanField(
                        default=True, verbose_name="Enforce installment order"
                    ),
                ),
                (
                    "allow_custom_amount",
                    models.BooleanField(
                        default=False, verbose_name="Allow custom amount"
                    ),
                ),
                (
                    "amount_step",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Payment amounts must be multiples of this value.",
                        verbose_name="Amount step (XAF)",
                    ),
                ),
                (
                    "late_fee_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Late fee rules"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Payment plan",
                "verbose_name_plural": "Payment plans",
            },
        ),
        migrations.CreateModel(
            name="RentalAgreement",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Start date"),
                ),
                (
                    "coverage_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Coverage end date"
                    ),
                ),
                (
                    "installment_status",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Installment status"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.paymentplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental agreement",
                "verbose_name_plural": "Rental agreements",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Amount (XAF)"
                    ),
                ),
                (
                    "months_covered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For monthly mode, fractional months if partial payment.",
                        max_digits=5,
                        null=True,
                        verbose_name="Months covered",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period start")),
                ("period_end", models.DateField(verbose_name="Period end")),
                (
                    "payment_date",
                    models.DateField(auto_now_add=True, verbose_name="Payment date"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mtn_momo", "MTN MoMo"),
                            ("orange_money", "Orange Money"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mobile provider"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Payer phone number"
                    ),
                ),
                (
                    "mobile_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Mobile money reference",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank name"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Check number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway response"
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.rentalagreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                ("order_index", models.PositiveSmallIntegerField(verbose_name="Order")),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="payments.paymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "unique_together": {("payment_plan", "order_index")},
            },
        ),
        migrations.AddIndex(
            model_name="rentalagreement",
            index=models.Index(
                fields=["unit", "is_active"], name="payments_re_unit_id_abe8df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalagreement",
            index=models.Index(
                fields=["tenant", "is_active"], name="payments_re_tenant__5e069c_idx"
            ),
        ),
    ]
