# Generated by Django 5.2 on 2026-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_paymentplan_rentalagreement_payment_installment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentTerm",
        ),
        migrations.AlterField(
            model_name="installment",
            name="order_index",
            field=models.PositiveIntegerField(verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="amount_step",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Payment amounts must be multiples of this value.",
                verbose_name="Amount step (XAF)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="max_months",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Maximum months per payment"
            ),
        ),
    ]
