# Generated by Django 5.2 on 2026-04-28 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_delete_paymentterm_alter_installment_order_index_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_agreements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terminated by",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Termination date"
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="termination_reason_text",
            field=models.TextField(blank=True, verbose_name="Termination reason"),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="termination_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("landlord_initiated", "Landlord Initiated"),
                    ("tenant_initiated", "Tenant Initiated"),
                    ("mutual_agreement", "Mutual Agreement"),
                    ("landlord_forced", "Landlord Forced (No Active Payment)"),
                    ("expired", "Auto‑expired"),
                ],
                max_length=30,
                null=True,
                verbose_name="Termination type",
            ),
        ),
    ]
