# Generated by Django 5.2 on 2026-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_rentalagreement_terminated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fee_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed breakdown of platform/gateway fees",
                verbose_name="Fee breakdown",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="net_landlord_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Amount that will be paid out to the landlord after fees",
                max_digits=10,
                null=True,
                verbose_name="Net amount to landlord (XAF)",
            ),
        ),
    ]
