# Generated by Django 5.2 on 2026-04-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_payment_fee_breakdown_payment_net_landlord_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Gateway reference"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_transaction_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Gateway transaction ID"
            ),
        ),
    ]
