# Generated by Django 5.2 on 2026-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_payment_gateway_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=0, help_text="XAF per month", max_digits=10
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of feature strings e.g., ['Up to 20 units', 'Priority support']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price"],
            },
        ),
    ]
