# Generated by Django 5.2 on 2026-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_subscriptionplan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={},
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_advanced_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_api_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_bulk_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_priority_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_properties",
            field=models.PositiveIntegerField(
                blank=True, help_text="Null = unlimited", null=True
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_units_per_property",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_units_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
