# Generated by Django 5.2 on 2026-06-17 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_rentalagreement_unique_unit_tenant_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rentalagreement",
            name="unique_unit_tenant",
        ),
    ]
