# Generated by Django 5.2 on 2026-06-17 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_remove_rentalagreement_unique_unit_tenant"),
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
        ("tenants", "0005_tenant_tenants_ten_is_disc_b7a12b_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rentalagreement",
            constraint=models.UniqueConstraint(
                fields=("unit", "tenant"), name="unique_unit_tenant"
            ),
        ),
    ]
