# Generated by Django 5.2 on 2026-06-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_rentalagreement_unique_unit_tenant"),
        (
            "properties",
            "0021_owner_subscription_end_date_owner_subscription_plan_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentplan",
            options={
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
            },
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this plan is private to this landlord. If null, it is a system plan.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="properties.owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="property",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this plan is specific to this property. owner must also be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="properties.property",
                verbose_name="Property",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="allow_custom_amount",
            field=models.BooleanField(
                default=False, verbose_name="Allow Custom Amount"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="allowed_monthly_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="e.g., [1,3,6]. Empty means any up to max_months.",
                verbose_name="Allowed Month Multiples",
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="amount_step",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Amount Step (XAF)"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="enforce_installment_order",
            field=models.BooleanField(
                default=True, verbose_name="Enforce Installment Order"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="late_fee_rules",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Late Fee Rules"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="max_months",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Maximum Months per Payment"
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Plan Name"),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="show_full_payment_option",
            field=models.BooleanField(
                default=True, verbose_name="Show Full Yearly Payment Option"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner__isnull", True), ("property__isnull", True)),
                    models.Q(("owner__isnull", False), ("property__isnull", True)),
                    models.Q(("owner__isnull", False), ("property__isnull", False)),
                    _connector="OR",
                ),
                name="paymentplan_valid_scope",
            ),
        ),
    ]
