# Generated by Django 5.2 on 2026-06-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0013_auditlog_disbursement_idempotencykey_ledgerentry_and_more"),
        ("properties", "0023_paymentownersplit"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="payment_split",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disbursements",
                to="properties.paymentownersplit",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["key", "resource_type"], name="payments_id_key_71dcd3_idx"
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="properties.owner",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="payments.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="disbursement",
            index=models.Index(fields=["status"], name="payments_di_status_9db171_idx"),
        ),
        migrations.AddIndex(
            model_name="disbursement",
            index=models.Index(
                fields=["payment_split", "status"],
                name="payments_di_payment_416a7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["entry_type"], name="payments_le_entry_t_d66fa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["payment", "entry_type"], name="payments_le_payment_90a622_idx"
            ),
        ),
    ]
