# Generated by Django 5.2 on 2026-06-27 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0014_disbursement_payment_split_and_more"),
        ("properties", "0024_termtemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="acceptance_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Acceptance token"
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Terms accepted at"
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="terms_accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_agreements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terms accepted by",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="terms_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template used for this agreement (snapshot stored in terms_text).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to="properties.termtemplate",
                verbose_name="Terms Template",
            ),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="terms_text",
            field=models.TextField(
                blank=True,
                help_text="Full text of the agreement terms (snapshot at creation).",
                verbose_name="Terms and conditions text",
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.CreateModel(
            name="AgreementAcceptance",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Accepted at"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User agent"
                    ),
                ),
                (
                    "terms_snapshot",
                    models.TextField(
                        help_text="Copy of terms at acceptance time.",
                        verbose_name="Terms snapshot",
                    ),
                ),
                (
                    "agreement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance_record",
                        to="payments.rentalagreement",
                        verbose_name="Agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Acceptance",
                "verbose_name_plural": "Agreement Acceptances",
            },
        ),
    ]
