# Generated by Django 5.2 on 2026-06-27 08:16
import uuid
from django.db import migrations, models

def generate_unique_acceptance_tokens(apps, schema_editor):
    """
    Generate a unique UUID for each existing RentalAgreement.
    This ensures there are no duplicates before adding the unique constraint.
    """
    RentalAgreement = apps.get_model('payments', 'RentalAgreement')
    for agreement in RentalAgreement.objects.all():
        agreement.acceptance_token = uuid.uuid4()
        agreement.save(update_fields=['acceptance_token'])

class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0015_rentalagreement_acceptance_token_and_more"),
    ]

    operations = [
        # Step 1: Populate acceptance_token for all existing rows
        migrations.RunPython(generate_unique_acceptance_tokens, reverse_code=migrations.RunPython.noop),
        # Step 2: Add the unique constraint
        migrations.AlterField(
            model_name="rentalagreement",
            name="acceptance_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Acceptance token",
            ),
        ),
    ]