# Generated by Django 5.2 on 2026-06-27 08:16

import uuid
from django.db import migrations, models


def fix_duplicate_acceptance_tokens(apps, schema_editor):
    RentalAgreement = apps.get_model('payments', 'RentalAgreement')
    # Find duplicates
    seen = {}
    for agreement in RentalAgreement.objects.all():
        if agreement.acceptance_token in seen:
            # Duplicate found: generate a new token
            agreement.acceptance_token = uuid.uuid4()
            agreement.save(update_fields=['acceptance_token'])
        else:
            seen[agreement.acceptance_token] = True


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0015_rentalagreement_acceptance_token_and_more"),
    ]

    operations = [
        # Fix any duplicate tokens before adding unique constraint
        migrations.RunPython(fix_duplicate_acceptance_tokens, reverse_code=migrations.RunPython.noop),
        # Then add unique constraint
        migrations.AlterField(
            model_name="rentalagreement",
            name="acceptance_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Acceptance token",
            ),
        ),
    ]